### ISSUE TITLE
Please provide jar for the recent release

### ISSUE THREAD

**Issue by jsbien** [dbmdz/iiif-server-demo#63]
Moreover perhaps README requires updating, as
`java -jar iiif-server-demo-4.0.3.jar ` gives `no main manifest attribute, in iiif-server-demo-4.0.3.jar`.

**Comment by morpheus-87** [comment]
Thank you for the issue! I just uploaded a runnable jar for the latest release and updated the `README`.

**Comment by stefan-it** [comment]
TEST
